package karina.lexer

object LanguageToken {

    // this list has to be ordered
    def allTokens(): List[Token] = {
        List(
          WhiteSpaceToken,
          CommentToken,
          StringToken,
          LiteralWord("fn"),
          LiteralWord("is"),
          LiteralWord("in"),
          LiteralWord("import"),
          LiteralWord("extends"),
          LiteralWord("override"),
          LiteralWord("native"),
          LiteralWord("true"),
          LiteralWord("false"),
          LiteralWord("virtual"),
          LiteralWord("break"),
          LiteralWord("return"),
          LiteralWord("object"),
          LiteralWord("let"),
          LiteralWord("if"),
          LiteralWord("else"),
          LiteralWord("new"),
          LiteralWord("while"),
          LiteralWord("for"),
          LiteralWord("super"),
          LiteralWord("self"),
          LiteralWord("int"),
          LiteralWord("float"),
          LiteralWord("bool"),
          LiteralWord("void"),
          LiteralToken("->"),
          LiteralToken(">="),
          LiteralToken("<="),
          LiteralToken("=="),
          LiteralToken("!="),
          LiteralToken("&&"),
          LiteralToken("||"),
          CharToken('+'),
          CharToken('-'),
          CharToken('*'),
          CharToken('/'),
          CharToken('%'),
          CharToken('>'),
          CharToken('<'),
          CharToken('!'),
          CharToken(':'),
          CharToken('='),
          CharToken('('),
          CharToken(')'),
          CharToken('{'),
          CharToken('}'),
          CharToken('['),
          CharToken(']'),
          CharToken(','),
          CharToken('.'),
          WordToken,
          RegexToken("number", "[0-9]+\\.?[0-9]*".r)
        )
    }
}
